# Generated by Django 4.2 on 2023-09-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='popularicecream',
            name='price',
            field=models.FloatField(),
        ),
    ]
