# Generated by Django 4.2.5 on 2023-09-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_icecream_price_alter_popularicecream_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
