# Generated by Django 4.2.5 on 2023-09-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopularIceCream',
        ),
        migrations.AlterModelOptions(
            name='icecream',
            options={},
        ),
        migrations.AddField(
            model_name='icecream',
            name='sold_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
