# Generated by Django 4.2 on 2023-09-23 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_delete_popularicecream_alter_icecream_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='icecream',
        ),
    ]
